[context.master]
  environment = { REACT_APP_API_URL = "https://api.don-key.finance", REACT_APP_ENV = "production"}
[context.staging]
  environment = { REACT_APP_API_URL = "https://api.don-key.finance", REACT_APP_ENV = "production"}
[context.dev]
  environment = { REACT_APP_API_URL = "https://dev-donkey-fph57.ondigitalocean.app", REACT_APP_ENV = "development" }
[context.deploy-preview]
  environment = { REACT_APP_API_URL = "https://dev-donkey-fph57.ondigitalocean.app", REACT_APP_ENV = "development"}
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200