[context.master]
  environment = { REACT_APP_GRAPHQL_URL = "https://don-strapi-g36tg.ondigitalocean.app/graphql", REACT_APP_API_URL = "https://staging-api.don-key.finance", REACT_APP_ENV = "production", REACT_APP_SHARE_LINK = "https://next.don-key.finance/share/"}
[context.staging]
  environment = { REACT_APP_GRAPHQL_URL = "https://don-strapi-g36tg.ondigitalocean.app/graphql", REACT_APP_API_URL = "https://api.don-key.finance", REACT_APP_ENV = "production", REACT_APP_SHARE_LINK = "https://next.don-key.finance/share/"}
[context."feature/*"]
  environment = { REACT_APP_GRAPHQL_URL = "https://don-strapi-g36tg.ondigitalocean.app/graphql", REACT_APP_API_URL = "https://api.don-key.finance", REACT_APP_ENV = "production", REACT_APP_SHARE_LINK = "https://next.don-key.finance/share/"}
[context.dev]
  environment = { REACT_APP_GRAPHQL_URL = "https://don-strapi-dev-nt48d.ondigitalocean.app/graphql", REACT_APP_API_URL = "https://dev-donkey-fph57.ondigitalocean.app", REACT_APP_ENV = "development", REACT_APP_SHARE_LINK = "https://don-next-dev.vercel.app/share/" }
[context.deploy-preview]
  environment = { REACT_APP_GRAPHQL_URL = "https://don-strapi-dev-nt48d.ondigitalocean.app/graphql", REACT_APP_API_URL = "https://dev-donkey-fph57.ondigitalocean.app", REACT_APP_ENV = "development", REACT_APP_SHARE_LINK = "https://don-next-dev.vercel.app/share/"}
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200