[build]
  command = "yarn build"
  publish = "public/"
[context.master.environment]
  GATSBY_STRAPI_URL = "https://cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x8d40C8a9F4bD8D23a244cEc57b20B7f8f43C5e0d"
  GATSBY_API_URL = "https://api.don-key.finance"
  GATSBY_APP_ENV = "production"
  GATSBY_SHOW_ADMIN = "false"
  GATSBY_SHARE_URL = "https://api.don-key.finance"
  GATSBY_REFERRAL_CONTRACT = 0x6482d0b6ec29eEf62289e829c7942Ad6E491d221
  GATSBY_REFERRAL_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/adeee11/referral-system"
[context.staging.environment]
  GATSBY_STRAPI_URL = "https://cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x8d40C8a9F4bD8D23a244cEc57b20B7f8f43C5e0d"
  GATSBY_API_URL = "https://api.don-key.finance"
  GATSBY_APP_ENV = "production"
  GATSBY_SHOW_ADMIN = "false"
  GATSBY_SHARE_URL = "https://api.don-key.finance"
  GATSBY_REFERRAL_CONTRACT = 0x6482d0b6ec29eEf62289e829c7942Ad6E491d221
  GATSBY_REFERRAL_SUBGRAPH = "https://api.thegraph.com/subgraphs/name/adeee11/referral-system"
[context."feature/*".environment]
  GATSBY_STRAPI_URL = "https://cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x8d40C8a9F4bD8D23a244cEc57b20B7f8f43C5e0d"
  GATSBY_API_URL = "https://api.don-key.finance"
  GATSBY_APP_ENV = "production"
  GATSBY_SHOW_ADMIN = "false"
[context.dev.environment]
  GATSBY_STRAPI_URL = "https://dev-cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x7eD3526d1C1bC42756B31b097761dd0E1f7EABE4"
  GATSBY_API_URL = "https://dev-api.don-key.finance"
  GATSBY_APP_ENV = "development"
  GATSBY_SHOW_ADMIN = "false"
[context.deploy-preview.environment]
  GATSBY_STRAPI_URL = "https://dev-cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x8d40C8a9F4bD8D23a244cEc57b20B7f8f43C5e0d"
  GATSBY_API_URL = "https://dev-api.don-key.finance"
  GATSBY_APP_ENV = "development"
  GATSBY_SHOW_ADMIN = "false"
[context.staging-with-admin.environment]
  GATSBY_STRAPI_URL = "https://cms.don-key.finance"
  GATSBY_STAKING_CONTRACT = "0x8d40C8a9F4bD8D23a244cEc57b20B7f8f43C5e0d"
  GATSBY_API_URL = "https://staging-api.don-key.finance"
  GATSBY_APP_ENV = "production"
  GATSBY_SHOW_ADMIN = "true"
