import { IFarmer } from "interfaces";
import image1 from "./images/image.svg";
import popeye from "./images/popeye.svg";

export const leaderBoardData: IFarmer[] = [
  {
    name: "Djony111",
    picture: image1.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Sally",
    picture: popeye.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Don",
    picture: image1.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Alex",
    picture: popeye.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Djony112",
    picture: image1.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Sally112",
    picture: popeye.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Don112",
    picture: image1.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Alexgroup",
    picture: popeye.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Djony-don",
    picture: image1.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
  {
    name: "Sallygroup12",
    picture: popeye.src,
    status: "active",
    poolAddress: "",
    GUID: "",
    descriptionTitle: "STRATEGY BSC only here pay min gas",
    description: "I’ll bring you to the well of new.",
    profit24hours: "-",
    profit7days: "-",
    profit: "-",
    pool_version: 1
  },
];
